### PR TITLE
[BUGFIX] Added removed getIconForState + needed functions (#244)

### LINKED ISSUE #244: Add Process failed
Due to heavy cleanup the "Add process" failed.

### PR DESCRIPTION
**Pull request by tomasnorre**
Resolves #244

### CODE REVIEW

File: view/process/class.tx_crawler_view_process_list.php [hunk 1]
```diff
@@ -304,6 +304,46 @@ protected function asMinutes($seconds)
...
+        }
+
+        return $this->getIcon($icon, $title);
+    }
+
+    /**
+     * Returns an imagetag for an icon
+     *
+     * @param string $icon
+     * @return string html tag for icon
```
Comment (srotsch) [inline view/process/class.tx_crawler_view_process_list.php]: The PHPdoc annotation for the second parameter is missing

File: view/process/class.tx_crawler_view_process_list.php [hunk 2]
```diff
@@ -304,6 +304,46 @@ protected function asMinutes($seconds)
...
+     */
+    protected function getIcon($icon, $title = '')
+    {
+        if (!empty($title)) {
+            $title = ' title="'.$title.'"';
+        }
+        return '<img src="'.$this->getIconPath().$icon.'.png" ' . $title . ' />';
```
Comment (srotsch) [inline view/process/class.tx_crawler_view_process_list.php]: Whitespaces around the concatenation operators missing here and in line 342; we should add this to the php-cs-fixer config.
